version: '3.5'

services:
  btls:
    build:
        context: .
        dockerfile: ./Dockerfile
    image: btls
    volumes:
      - ./src:/app/src
      - ./config.properties:/app/config.properties
    container_name: btls
  
  mqtt:
    image: library/eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    container_name: mqtt